name: cake_ordering_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  cloud_firestore:
  firebase_auth:
  google_sign_in: ^6.1.6
  logger: ^2.0.2+1
  flutter_hooks:
  hooks_riverpod:
  google_fonts: ^8.0.2
  url_strategy:
  url_launcher: ^6.2.4
  flutter_svg:
  sign_button:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

dependency_overrides:
  path_provider: ^2.1.5
  path_provider_android: ^2.2.17
  path_provider_windows: ^2.3.0
  url_launcher_android: ^6.3.29
  win32: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
