// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqysrMo0y7P0UZMjEBFP9z91g33B60nzQ',
    appId: '1:182640302567:web:eac8a4b0335bed817b0542',
    messagingSenderId: '182640302567',
    projectId: 'cake-delight-21f46',
    authDomain: 'cake-delight-21f46.firebaseapp.com',
    storageBucket: 'cake-delight-21f46.appspot.com',
    measurementId: 'G-YGGTL77F2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4erxl5vTBcAluk-JB1ep7UpBU15gKHfU',
    appId: '1:182640302567:android:10a19e6519c3f1cd7b0542',
    messagingSenderId: '182640302567',
    projectId: 'cake-delight-21f46',
    storageBucket: 'cake-delight-21f46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqu_OgzKuZvUhQy1wpj2ZKLdwbU69m50E',
    appId: '1:182640302567:ios:2178d5d0f0b6acda7b0542',
    messagingSenderId: '182640302567',
    projectId: 'cake-delight-21f46',
    storageBucket: 'cake-delight-21f46.appspot.com',
    iosClientId: '182640302567-tq8jfma46ditl8ft4guqsokjjaja44k8.apps.googleusercontent.com',
    iosBundleId: 'com.codingliquids.cakeOrderingApp',
  );
}
